name = "web-archive"
pages_build_output_dir = "../../dist/service"
compatibility_flags = [ "nodejs_compat_v2" ]
compatibility_date = "2024-10-21"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "web-archive"

[[d1_databases]]
binding = "DB"
database_name = "web-archive"
database_id = "ddc7b449-780b-43d9-9920-d7dcfde2407c"
migrations_dir = './src/sql/migrations'

[ai]
binding = "AI"
